(cd cra && amplify-dev codegen models)
(cd next && amplify-dev codegen models)
(cd no-cra && amplify-dev codegen models)
(cd no-react && amplify-dev codegen models)
(cd no-typescript && amplify-dev codegen models)
