(cd cra && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql && cp LazyApp.tsx src/App.tsx)
(cd next && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql && cp lazyindex.tsx pages/index.tsx)
(cd no-cra && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql && cp LazyApp.tsx src/App.tsx)
(cd no-react && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql && cp lazyindex.ts src/index.ts)
(cd no-typescript && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
