(cd cra && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
(cd next && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
(cd no-cra && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
(cd no-react && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
(cd no-typescript && npm link aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
