(cd cra && npm unlink --no-save aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
(cd next && npm unlink --no-save aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
(cd no-cra && npm unlink --no-save aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
(cd no-react && npm unlink --no-save aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
(cd no-typescript && npm unlink --no-save aws-amplify @aws-amplify/core @aws-amplify/datastore @aws-amplify/auth @aws-amplify/ui-components @aws-amplify/api @aws-amplify/api-graphql)
